Create layout-1
dlinev/admin-panel-makeup pull request #1
Opened 2022-01-16 10:21 UTC by dlinev

2022-01-19 23:04 UTC, Muslik approved these changes

2022-01-19 23:04 UTC, Muslik commented on layout.html
> +<!DOCTYPE html>
Единственный html файл в проекте должен называться index.html

2022-01-19 23:22 UTC, Muslik requested changes

2022-01-19 23:22 UTC, Muslik commented on layout.css
> +    margin-bottom: 2rem;
Этот блок является внутренним и очень некрасиво когда ребенок задает отступы для родителя.

2022-01-19 23:22 UTC, Muslik commented on layout.css
> +    margin-bottom: 2rem;
У блока по БЭМ не должно быть отступов. Они должны быть у элементов.
В вашем случае нужно указать отступы для блока title.

У title будет два класса. <div class="title header__title"></div>

В таком случае мы можем основные стили задать блоку .title, а его отступы (margin) указать в классе header__title. И получается что title является блоком сам по себе, но в контексте данной страницы он является еще и элементом

2022-01-20 07:30 UTC, dlinev commented on layout.html
> +<!DOCTYPE html>
Поправил

2022-01-20 08:24 UTC, dlinev commented on layout.css
> +    margin-bottom: 2rem;
Исправил

2022-01-20 09:23 UTC, Muslik approved these changes
Мелкие замечания, будет хорошо если поправите

2022-01-20 09:23 UTC, Muslik commented on index.html
> +    <div class="title title__header">
title__header - не может быть )
родительский-блок__элемент

Поэтому header__title.

2022-01-20 09:23 UTC, Muslik commented on layout.css
> +    padding: 0;
Там изначально padding: 0, нет смысла его обнулять

2022-01-20 09:23 UTC, Muslik commented on layout.css
> +  .filter {
Такой же кейс с отступами в блоке как и раньше

2022-01-20 10:04 UTC, dlinev commented on index.html
> +    <div class="title title__header">
cделал

2022-01-20 10:45 UTC, dlinev commented on layout.css
> +  .filter {
Исправил

2022-01-20 12:31 UTC, merged