Makeup input
dlinev/admin-panel-makeup pull request #3
Opened 2022-01-27 15:41 UTC by dlinev

2022-01-29 17:45 UTC, Muslik requested changes
Прикреплю видео

2022-01-29 17:45 UTC, Muslik commented on index.html
> +    function setFocus(num) {
В ДЗ это не входит. Зачем это тут?

2022-01-29 17:45 UTC, Muslik commented on index.html
> +        <div class="input-block">
nit: Ну это скорее input wrapper какой нибудь

2022-01-29 17:45 UTC, Muslik commented on index.html
> +            <input class="input-block__item input-block__item-error" id="block-2" type="datetime" placeholder="Введите" value="06.12.2021"></input>
error - модификатор? Тогда он неправильно указан

2022-01-29 17:45 UTC, Muslik commented on index.html
> +        <input class="input-block__item input-block__item-lock" id="block-3" type="datetime" placeholder="Введите" value="06.12.2021"></input>
Все эти id у инпутов не нужны

2022-01-31 13:33 UTC, dlinev commented on index.html
> +        <input class="input-block__item input-block__item-lock" id="block-3" type="datetime" placeholder="Введите" value="06.12.2021"></input>
поправил все замечания

2022-02-01 20:41 UTC, Muslik approved these changes
Маленькое замечание. Но нужно поправить

2022-02-01 20:41 UTC, Muslik commented on blocks/input.css
> +  margin-bottom: 0.5rem;
Для чего этот margin тут? У вас же инпут весь внутри label лежит. Значит этот margin бесполезен

2022-02-01 20:41 UTC, Muslik commented on blocks/input.css
> +  margin-bottom: 0.5rem;
Между label и инпутом нужен отступ. Сейчас его нет

2022-02-02 10:23 UTC, merged