Makeup search bar
dlinev/admin-panel-makeup pull request #4
Opened 2022-02-01 07:31 UTC by dlinev

2022-02-01 20:49 UTC, Muslik requested changes
Фокус бы поправить только

2022-02-01 20:49 UTC, Muslik commented on blocks/search-bar.css
> +  margin-right: 0.5rem;
Задайте padding блоку обертке вместо этого.

2022-02-01 20:49 UTC, Muslik commented on blocks/search-bar.css
> +  margin-right: 0.5rem;
https://ibb.co/zHXkHtR Выглядит не очень. Фокус должен быть у всего элемента. А для этого либо кастомный фокус пилить, либо как нибудь в input абсолютами кнопку и иконку положить. Иконку поиска можно вообще с помощью background-image в input закинуть

2022-02-02 11:11 UTC, dlinev commented on blocks/search-bar.css
> +  margin-right: 0.5rem;
Поправил

2022-02-04 21:40 UTC, Muslik approved these changes
Good

2022-02-07 12:08 UTC, merged