Makeup checkbox radio
dlinev/admin-panel-makeup pull request #5
Opened 2022-02-02 14:09 UTC by dlinev

2022-02-04 23:28 UTC, Muslik requested changes
Checkbox и radio должны быть кастомными. Сейчас они не такие как на макете

2022-02-07 12:05 UTC, dlinev commented
Ошибку понял, переделал

2022-02-08 18:20 UTC, Muslik requested changes
https://ibb.co/Dr6N2M6 найдите отличия как говорится...

2022-02-09 12:26 UTC, dlinev commented
> https://ibb.co/Dr6N2M6 найдите отличия как говорится...

Seek and destroy

2022-02-13 14:28 UTC, Muslik requested changes
Есть замечания.

2022-02-13 14:28 UTC, Muslik commented on blocks/checkbox-radio.html
> +        <div class="checkbox checkbox_empty">
Неа. Не пойдет. checkbox_empty вы сделали модификатором и им почему то двигаете checkbox. Блок checkbox не может иметь абсолютное позиционирование.

2022-02-13 14:28 UTC, Muslik commented on blocks/checkbox-radio.html
> +        <div class="checkbox checkbox_empty">
Соответственно для div не нужен ни модификатор empty, ни модификатор checked

2022-02-13 14:28 UTC, Muslik commented on blocks/checkbox-radio.html
> +        <div class="checkbox checkbox_empty">
Я должен взять важ checkbox, вставить куда угодно на страницу и он будет себя вести как обычный блок.
В вашем случае это не работает: https://ibb.co/202xvmG

2022-02-16 14:43 UTC, dlinev commented on blocks/checkbox-radio.html
> +        <div class="checkbox checkbox_empty">
поправил

2022-02-20 05:23 UTC, Muslik requested changes
Ваша работа отличается с тем что сейчас в github pages. Плюс нужно создать переиспользуемый чекбокс и радио размером 16x16. В вашей работе этого нет.

2022-02-20 05:23 UTC, Muslik commented on blocks/checkbox-radio.html
> +        <div class="checkbox">
А. У вас еще различия между тем что в github pages и вашей работой

2022-02-20 05:23 UTC, Muslik commented on blocks/checkbox-radio.html
> +        <div class="checkbox">
А вот теперь представьте как я ваш чекбокс должен переиспользовать. https://ibb.co/qjGwCVg.
У вас какой то единый блок 80x40.

Сам чекбокс должен быть размера 16x16. И я его должен без проблем вставить куда угодно на страницу. В вашем случае это сделать невозможно. 
Должен быть блок в котором есть input и label. И этот блок я могу скопировать и вставить куда то еще.

2022-02-21 12:28 UTC, dlinev commented
поправил

2022-02-22 22:33 UTC, Muslik requested changes
Так как никакую ссылку на github pages от вас я не увидел, поискал сам. https://dlinev.github.io/admin-panel-makeup/blocks/checkbox-radio.html.
Результат там и то что я вижу у вас в верстке отличается.

2022-02-24 10:05 UTC, dlinev commented
Проблема только в неправильных pages? Я поправил

2022-03-04 08:10 UTC, Muslik approved these changes

2022-03-04 12:16 UTC, merged