Makeup button
dlinev/admin-panel-makeup pull request #6
Opened 2022-02-08 15:09 UTC by dlinev

2022-02-08 18:22 UTC, Muslik commented
Жду github pages

2022-02-08 18:40 UTC, Muslik requested changes
Нет ссылки на github pages. Размеры иконок не соответствуют макету. (Также проверьте размеры кнопок). На макете не указано поведение про hover, не нужно его реализовывать. Потому что сейчас смотрится не очень.

2022-02-08 18:40 UTC, Muslik commented on blocks/button.html
> +          <div class="button">
Для чего лишняя обертка??
 У вас есть тег button. Вот ему и назначьте этот класс.

2022-02-08 18:40 UTC, Muslik commented on blocks/button.html
> +          <div class="button">
Модификаторы вида fill fill-big не особо хорошо выглядят, потому что они ничего особо не описывают.
У вас есть несколько параметров: тема (стиль), размер. Вот и сделайте отдельный модификаторы для них:
.button
.button_theme_primary (название темы можете придумать свое)
.button_theme_secondary,
...
.button_size_large
.button_size_small

Теперь рассматриваем случай когда завтра приходит дизайнер и говорит что есть новый размер (tiny)
Что нужно сделать в вашем случае:

.button__item_fill-tiny
.button__item_transparent-tiny
И так для каждой темы. Что нужно будет сделать мне:

.button_size_tiny
Все. Модификаторы размера и темы никак не зависят друг от друга. Также и с темой. Добавится новая тема, добавится 1 модификатор всего лишь, а не все варианты для каждого размера

2022-02-08 18:40 UTC, Muslik commented on blocks/button.html
> +          <div class="button">
Помните что button это независимый блок. он не должен знать о том где его будут использовать, поэтому не стоит ему задавать отступы.

2022-02-08 18:40 UTC, Muslik commented on blocks/button.css
> +  /* чот не пригодилось*/
В таком случае его удалить )

2022-02-09 12:34 UTC, dlinev commented
> Жду github pages

https://dlinev.github.io/admin-panel-makeup/
вот беж

2022-02-09 17:14 UTC, dlinev commented
Все переделал по рекомендациям

2022-02-13 01:47 UTC, Muslik requested changes
Прикрепил видео в тг

2022-02-16 13:54 UTC, dlinev commented
попытался сделать по рекомендациям на видео

2022-02-20 05:10 UTC, Muslik requested changes
Поработайте над именованием классов. Отступы между иконками и текстом не соответствуют макету. У кнопок на макете есть font-family

2022-02-20 05:10 UTC, Muslik commented on blocks/button.css
> +  margin-bottom: 16px;
Не может быть такого модификатора у блока. Это внешний отступ который может устанавливать только родитель который использует эту кнопку.

2022-02-20 05:10 UTC, Muslik commented on blocks/button.css
> +.button__item {
Я не вижу стили назначенные для класса .button
Вот эти стили должны быть именно в нем.

2022-02-20 05:10 UTC, Muslik commented on blocks/button.html
> +      <div class="button__column">
Как может быть элемент column блока button если выше у вас блока  button нет.

2022-02-20 05:10 UTC, Muslik commented on blocks/button.html
> +        <div class="button__items button_items_space_bottom">
button_items_space_bottom - ненужный класс.  Этот отступ можно задавать в класс элемента. И обнулить у последнего

2022-02-21 08:22 UTC, dlinev commented on blocks/button.css
> +  margin-bottom: 16px;
Не очень понятно как в flexbox сделать отступы между элементами внутри. Только если установить явно высоту блока и сделать justify-content: space-around. Но что-то мне подсказывая, что это так себе решение.

2022-02-21 08:51 UTC, dlinev commented
поправил

2022-02-22 22:44 UTC, Muslik commented on blocks/button.css
> +  margin-bottom: 16px;
Допустим у вас есть блок который использует эту кнопку: .container

В таком случае отступ вы можете задать через элемент:

```html
<div class="container">
  <button class="button container__button"></button>
</div>
```

button у вас остается независимым, а о его отступах заботится родитель который его использует

2022-02-22 22:48 UTC, Muslik approved these changes
Отступ между текстом и иконкой в маленькой кнопке должен быть 4px а не 6px

2022-02-24 09:05 UTC, merged