Create list-mock
dlinev/admin-panel-makeup pull request #7
Opened 2022-02-21 13:43 UTC by dlinev

2022-02-21 18:39 UTC, Muslik requested changes

2022-02-21 18:39 UTC, Muslik commented on mocks/list.js
> +const ordersJson = `
Не нужно делать это строкой. Это обычный массив

2022-02-21 18:39 UTC, Muslik commented on mocks/utils.js
> +console.log(getOrderByStatus(JSON.parse(ordersJson), "Выполнен"));
Соответственно если ordersJson будем массив, то JSON.parse тут не нужен.

2022-02-21 18:39 UTC, Muslik commented on mocks/utils.js
> +const getOrderByStatus = function (orders, valueStatus) {
Предложение: Тут можно тоже стрелочную функцию написать раз уж вы начали :)
```javascript
const getOrderByStatus = (orders, valueStatus) => {
  return orders.filter((order) => {
    return order.orderStatus === valueStatus;
  })
};
```

2022-02-21 18:39 UTC, Muslik commented on mocks/utils.js
> +const getOrderByStatus = function (orders, valueStatus) {
А можно вообще в одну строчку :D
```javascript
const getOrderByStatus = (orders, valueStatus) => orders.filter((order) => order.orderStatus === valueStatus)
```

Но это так. Для сведения )

2022-02-22 07:56 UTC, dlinev commented on mocks/utils.js
> +const getOrderByStatus = function (orders, valueStatus) {
мне пока такие конструкции с трудом даются )

2022-02-22 08:00 UTC, dlinev commented on mocks/list.js
> +const ordersJson = `
так в задании явно написано про Json "Придумайте и разместите внутри
файла list.js json-код примера списка
товаров."
Json = строка, или нет?

2022-02-22 08:11 UTC, dlinev commented on mocks/list.js
> +const ordersJson = `
если убрать строку prettier заменяет json формат на js объект

2022-02-22 08:12 UTC, dlinev commented on mocks/list.js
> +const ordersJson = `
тогда не понятно зачуем называть это json-mock )

2022-02-22 22:24 UTC, Muslik commented on mocks/list.js
> +const ordersJson = `
Так json это Javascript object notation. Любой json это валидный js объект

2022-02-22 22:26 UTC, Muslik approved these changes

2022-02-22 22:26 UTC, Muslik commented on mocks/utils.js
> +const _STATUS = "Выполнен";
Тогда уже STATUS_COMPLETED

2022-02-24 08:11 UTC, merged